<a href="https://colab.research.google.com/github/Fa861001/Razumikhin/blob/master/CrossCovariance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import pandas as pd
import numpy as np
#receiving the inputs
t=int(input('enter the size of the sample '))
n=int(input('enter the size of the assets '))
#random generating the signals and returns matrices
sigs = np.random.randint(n,size=(t,n))
rets = np.random.randint(n,size=(t,n))
#first step estimation
sig1=np.identity(n)
sig2=np.identity(n)
sig3=np.cov(sigs,rets)
fi=(sig3.trace())/n
ro=(sig3.sum()-sig3.trace())/(n*(n-1))
sig3=fi*(np.identity(t))+ro*(np.ones([t,t])-np.identity(t))
#generalized estimation
sig1=np.cov(sigs)
sig2=np.cov(rets)
from scipy.linalg import fractional_matrix_power
a = fractional_matrix_power(sig1, 0.5)
b= fractional_matrix_power(sig2, 0.5)
sig3=np.dot(b,sig3,a)
print(sig1)
print(sig2)
print(sig3)









enter the size of the sample 6
enter the size of the assets 14
[[11.3021978   2.7032967   1.78021978 -2.64835165  7.52197802 -1.44505495]
 [ 2.7032967  18.43956044  0.13186813 -4.01098901 -2.27472527 -3.64835165]
 [ 1.78021978  0.13186813 12.43956044  4.75824176 -0.50549451  3.58241758]
 [-2.64835165 -4.01098901  4.75824176 11.34065934 -7.02197802  1.79120879]
 [ 7.52197802 -2.27472527 -0.50549451 -7.02197802 21.56593407  1.28021978]
 [-1.44505495 -3.64835165  3.58241758  1.79120879  1.28021978  9.25824176]]
[[14.02747253  7.88461538 -7.92307692  1.26923077 -0.56593407  0.42307692]
 [ 7.88461538 16.26923077  3.07692308  1.88461538 -1.42307692 -0.11538462]
 [-7.92307692  3.07692308 23.53846154 -5.69230769 -3.38461538 -2.92307692]
 [ 1.26923077  1.88461538 -5.69230769 18.88461538 -8.73076923  3.96153846]
 [-0.56593407 -1.42307692 -3.38461538 -8.73076923 16.02747253 -7.88461538]
 [ 0.42307692 -0.11538462 -2.92307692  3.96153846 -7.88461538 18.57692308]]
[[ 4.63118121e+01  1.61314591e+01 -